import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Processor('workflows')
export class WorkflowProcessor extends WorkerHost {
  private readonly logger = new Logger(WorkflowProcessor.name);

  constructor(private prisma: PrismaService) {
    super();
  }

  async process(job: Job<any, any, string>): Promise<any> {
    this.logger.log(`Processing workflow execution job: ${job.id}`);
    const { workflowId, triggerData, tenantId } = job.data;

    try {
      this.logger.log(`Executing Workflow: ${workflowId} for Tenant: ${tenantId}`);
      
      const workflow = await this.prisma.workflow.findUnique({
        where: { id: workflowId, tenantId },
        include: { actions: { orderBy: { orderIndex: 'asc' } } }
      });

      if (!workflow) {
        throw new Error(`Workflow ${workflowId} not found`);
      }

      for (const action of workflow.actions) {
        this.logger.log(`Executing Action [${action.actionType}]: ${action.id}`);
        const actionData = (action.actionData as any) || {};

        switch (action.actionType) {
          case 'SEND_EMAIL':
            this.logger.log(`[SEND_EMAIL] Sending email to: ${actionData.to || 'recipient'} - Subject: ${actionData.subject || 'Notification'}`);
            // Log as an activity in the timeline if contact or deal is available
            await this.prisma.activity.create({
              data: {
                tenantId,
                type: 'EMAIL',
                title: `Automated Email: ${actionData.subject || 'Workflow Notification'}`,
                content: `Sent to: ${actionData.to || 'recipient'}\n\n${actionData.body || 'Automated message from workflow'}`,
                contactId: actionData.contactId || null,
                dealId: actionData.dealId || null,
              }
            }).catch(e => this.logger.warn(`Could not log email activity: ${e.message}`));
            break;
            
          case 'CREATE_RECORD':
            this.logger.debug(`[CREATE_RECORD] Creating record in object ${actionData.objectTypeId}`);
            if (actionData.objectTypeId) {
              await this.prisma.customRecord.create({
                data: {
                  tenantId,
                  customObjectId: actionData.objectTypeId,
                  data: actionData.recordData || {}
                }
              });
            }
            break;
            
          case 'CREATE_ACTIVITY':
            this.logger.log(`[CREATE_ACTIVITY] Logging ${actionData.type || 'NOTE'} activity`);
            await this.prisma.activity.create({
              data: {
                tenantId,
                type: actionData.type || 'NOTE',
                title: actionData.title || 'Workflow Activity',
                content: actionData.content || 'Automated activity generated by workflow.',
                contactId: actionData.contactId || null,
                companyId: actionData.companyId || null,
                dealId: actionData.dealId || null,
              }
            }).catch(e => this.logger.warn(`Could not log activity: ${e.message}`));
            break;

          case 'HTTP_REQUEST':
            const url = actionData.url;
            this.logger.debug(`[HTTP_REQUEST] Fetching ${url}`);
            if (url) {
              try {
                const res = await fetch(url, {
                  method: actionData.method || 'GET',
                  headers: { 'Content-Type': 'application/json', ...(actionData.headers || {}) },
                  body: actionData.body ? JSON.stringify(actionData.body) : undefined,
                });
                this.logger.debug(`[HTTP_REQUEST] Result: ${res.status}`);
              } catch (err) {
                this.logger.error(`[HTTP_REQUEST] Failed: ${err.message}`);
              }
            }
            break;
            
          default:
            this.logger.warn(`Unknown action type: ${action.actionType}`);
            await new Promise(resolve => setTimeout(resolve, 100));
        }
      }

      this.logger.log(`Workflow ${workflowId} completed successfully`);
      return { status: 'completed', workflowId };
    } catch (error) {
      this.logger.error(`Workflow ${workflowId} failed: ${error.message}`);
      throw error;
    }
  }
}
